<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <PackageId>Bllueprint.Core.Api</PackageId>
    <Version>1.0.0</Version>
    <Authors>Nubaum</Authors>
    <Description>A nice nuget package for DDD - Api layer</Description>
    <PackageTags>DDD domain-driven-design clean-architecture domain core csharp dotnet bllueprint</PackageTags>
    <RepositoryUrl>https://github.com/bllueprint/Bllueprint.Core.Api</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>

    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>

    <PackageIcon>assets/icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore.Microsoft" />
    <PackageReference Include="Bllueprint.Core.Application" />
  </ItemGroup>

  <ItemGroup>
    <None Include="assets/icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Bllueprint.Core.Api.Tests" />
  </ItemGroup>

</Project>